version: '3.9' # Updated version

services:
  traffic-db:
    image: mariadb:10.5
    container_name: traffic-db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - traffic-network
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_password
      - MYSQL_DATABASE=traffic
      - MYSQL_USER=traffic
      - MYSQL_PASSWORD=traffic-password
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

  statistics-app:
    build:
      context: statistics
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    networks:
      - traffic-network
    depends_on:
      - traffic-db

networks:
  traffic-network:
    driver: bridge

volumes:
  db_data: